server:
  port: 9002
spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        #server-addr: http://192.168.168.128:8848 配置nacos地址
        server-addr: http://192.168.168.128:1111 #本机
management:
  endpoints:
    web:
      exposure:
        include: '*'