server:
  port: 9092
spring:
  application:
    name: storage-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.168.128:1111
    alibaba:
      seata:
        tx-service-group: storage-service-group
  datasource:
    url: jdbc:mysql://localhost:3306/seata_storage?serverTimezone=Asia/Shanghai
    username: root
    password: root
logging:
  level:
    io:
      seata: debug
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl