server:
  port: 80
spring:
  application:
    name: OrderHystrixFeign80
eureka:
  client:
    #false表示不同注册中心注册自己
    register-with-eureka: false #true
    #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: true
    service-url:
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
      #集群版
      #defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
      #单机版
      defaultZone: http://eureka7001.com:7001/eureka
#设置feign客户端超时时间(OpenFeign默认支持Ribbon)

feign:
  client:
    config:
      cloud-hystrix-payment:
        #指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间
        connectTimeout: 3000
        #指的是建立连接后从服务器读取到可用资源所用的时间
        readTimeout: 4000
        loggerLevel: full
  hystrix:
    enabled: true
logging:
  level:
    # Feign logging only responds to the DEBUG level.
    com.atguigu.springcloud.service.PaymentFeignService: DEBUG
