server:
  port: 9527    #8080
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: payment_routh #payment_route #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001 #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址,uri的协议是lb,表示启用Gateway的负载均衡功能
          order: 9000
          predicates:
            - Path=/payment/find/** #断言，路径相匹配的进行路由
        - id: payment_routh2
          #uri: http://localhost:8001
          uri: lb://cloud-payment-service
          order: 9001
          predicates:
            - Path=/payment/lb/**
            - After=2020-07-12T16:26:12.049+08:00[Asia/Shanghai]
            #- Cookie=username,hh
      discovery:
        locator:
          enabled: true  #开启从注册中心动态创建路由的功能
eureka:
  client:
    #false表示不同注册中心注册自己
    register-with-eureka: true
    #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: true
    service-url:
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
      #集群版
      #defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
      #单机版
      defaultZone: http://eureka7001.com:7001/eureka
