server:
  port: 9002
spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: http://192.168.120.128:8848 #配置nacos地址
management:
  endpoints:
    web:
      exposure:
        include: '*'